spring:
  application:
    name: cloud-zipkin

server:
  port: 8003

eureka: 
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
      
management:
  metrics:
    web:
      server:
        auto-time-requests: false    
      
  
      