spring:
  application:
    name: cloud-client-oauth2
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    org.springframework: debug   #开启Spring日志打印级别

server: 
  port: 9012
  
eureka: 
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

