spring:
  application:
    name: cloud-client-feign
  zipkin: #链路追踪
    base-url: http://localhost:8003
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

server: 
  port: 9001

eureka: 
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

#开启Feign熔断器功能
feign: 
  hystrix: 
    enabled: true
  client:
    config:
      feignName: 
        connect-timeout: 5000
        read-timeout: 5000

#ribbon的超时时间, 防止feign调用超时
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 15000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试