spring:
  application:
    name: cloud-client-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

server: 
  port: 9001

eureka: 
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
      
  
      