spring:
  application:
    name: cloud-zuul
  zipkin: #链路追踪
    base-url: http://localhost:8003
    
server: 
  port: 9101

eureka: 
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

zuul:
  retryable: true #开启重试功能
  routes:
    api-a: 
      path: /api/feign/**
      # 敏感头 代表不过滤任何信息 这边必需设置，否则OAuth2服务会对该URL报Unauthorized
      sensitive-headers: 
      service-id: cloud-client-feign #转发到app-name为cloud-client-feign微服务客户端
    api-b: 
      path: /api/ribbon/**
      service-id: cloud-client-ribbon #转发到app-name为cloud-client-ribbon微服务客户端
    #配置OAuth2权限服务
    api-auth:
      path: /auth/**
      # 敏感头 代表不过滤任何信息
      sensitive-headers:
      service-id: cloud-client-oauth2

  #添加代理头
  add-proxy-headers: true

ribbon: 
  MaxAutoRetries: 2 #重试次数
  MaxAutoRetriesNextServer: 1 #其他服务重试次数
  
