spring:
  application:
    name: cloud-client-ribbon
  zipkin: #链路追踪
    base-url: http://localhost:8003
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

server: 
  port: 9002

eureka: 
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

