spring:
  application:
    name: cloud-service
  zipkin: #链路追踪
    base-url: http://localhost:8003

server:
  port: 8002

eureka: 
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
      
  
      