spring:
  application:
    name: cloud-service
  zipkin: #链路追踪
    base-url: http://localhost:8003

server:
  port: 8002

eureka: 
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
      
security:
  oauth2:
    resource:
      id: cloud-service
      # 指定用户信息地址
      user-info-uri: http://localhost:9012/auth/user
      prefer-token-info: false  
      